### ISSUE TITLE
Quebras de linha sendo postadas literalmente

### ISSUE THREAD

**Issue by cadusilva** [amosbatista/ursal-acessivel#14]
Excelente a última atualização, está verificando os toots corretamente e enviando as DM.

Porém o texto delas, quando publicado, está mostrando `\n` literalmente na mensagem em vez de quebrar a linha.

```
DM_MSG: "Alto lá! :policia: \\n\\nCom licença, @@$${post.user.userName}.\\n\\nReparei que este post ($${post.url}) tem uma imagem ou vídeo sem descrição. Como na $${process.env.INSTANCE_NAME} temos muito apreço por abrir as portas e incluir pessoas com deficiência visual, gostaria de reforçar com você este acordo de acessibilidade.\\n\\nPor favor, veja se é possível revisar e editar seu toot (via app ou web), adicionando descrição nas mídias.\\n\\nMuito obrigado por sua compreensão e apoio!"
```

Outra coisa é que tive que colocar o `@` duas vezes em `@@$${post.user.userName}`, caso contrário aparecia o nome do usuário em texto puro em vez de com link e mencionando-o.

**Comment by cadusilva** [comment]
Como o post sai quando é publicado:

```
Alto lá! :policia: \n\nCom licença, fulano.\n\nReparei que este post (https://bolha.one/@fulano/12345678901234567890) tem uma imagem ou vídeo sem descrição. Como na Bolha.one temos muito apreço por abrir as portas e incluir pessoas com deficiência visual, gostaria de reforçar com você este acordo de acessibilidade.\n\nPor favor, veja se é possível revisar e editar seu toot (via app ou web), adicionando descrição nas mídias.\n\nMuito obrigado por sua compreensão e apoio!
```

**Comment by amosbatista** [comment]
Olá, este problema é corrigido removendo as "\" extras do arquivo .env.
Ex: 
`DM_MSG: "Alto lá! :policia: \n\nCom licença, @@$${post.user.userName}.\n\nReparei que este post ($${post.url}) tem uma imagem ou vídeo sem descrição. Como na $${process.env.INSTANCE_NAME} temos muito apreço por abrir as portas e incluir pessoas com deficiência visual, gostaria de reforçar com você este acordo de acessibilidade.\\n\\nPor favor, veja se é possível revisar e editar seu toot (via app ou web), adicionando descrição nas mídias.\n\nMuito obrigado por sua compreensão e apoio!"
`

**Comment by cadusilva** [comment]
Fiz as alterações e vou testar aqui, obrigado!
