### ISSUE TITLE
Log na timeline

### ISSUE THREAD

**Issue by cadusilva** [amosbatista/ursal-acessivel#15]
Percebi que a última atualização levou para a timeline as atualizações que antes apareciam no console de log. Enquanto essa não é uma ideia ruim quando o perfil destinado ao bot não é usado para outros fins, no caso dele ser usado para outras coisas torna a novidade em algo não desejado e que flooda as pessoas que seguem o robô.

No caso, diariamente publico gráficos mostrando a porcentagem de mídias descritas localmente e na federação. Aos sábados, sai um ranking das instâncias que mais descreveram mídias durante a semana.

Sei que o perfil ser usado para outras finalidades não está no escopo do bot, o que explica a mudança, mas fica a mera sugestão de devolver as mensagens de log para o console em vez da timeline.

**Comment by amosbatista** [comment]
Olá, Cadú. Obrigado por ter avisado.

Realizei uma correção na PR https://github.com/amosbatista/ursal-acessivel/pull/17, onde eu deixo estas postagens localmente (apenas eu posso visualizar.).

**Comment by amosbatista** [comment]
Sobre a questão do log:

- Adorei a sua sugestão de postar estes dados na timeline. Se houver algum lugar de onde eu consiga ler estas informações, aí eu não precisaria fazer este trabalho, apenas leria os dados e montaria um toot diário ou semanal.
- Eu tive uma ideia parecida com esta: ao invés de postar as atualizações de tudo o que o robô estava fazendo, escrever um toot de relatório diário (quantos posts eu achei sem descrição, quantos erros, etc). Ele está neste PR, mas há um problema na rotina de leitura de Atividade que não estou conseguindo resolver (apesar de toda a lógica já estar pronta). (https://github.com/amosbatista/ursal-acessivel/pull/18)

**Comment by cadusilva** [comment]
Pronto, ficou ótimo. É possível que essas mensagens do funcionamento do bot ocupem apenas uma "conversa" na página de DMs? Assim as DMs de notificação de usuários não se perdem em meio às mensagens de funcionamento do próprio bot.

**Comment by amosbatista** [comment]
Revisando as issues: Esta issue foi finalizada na PR https://github.com/amosbatista/ursal-acessivel/pull/28
